### ISSUE TITLE
Building error (‘sim’ was not declared in this scope ...)

### ISSUE THREAD

**Issue by previtus** [eaplatanios/nel_framework#3]
Hi,
I am having some issues with setting up the python api via `python setup.py install` 

I am getting:
```
nel/simulator.cpp: In function ‘PyObject* nel::Py_BuildAgentState(const nel::agent_state*)’:
nel/simulator.cpp:25:50: error: ‘sim’ was not declared in this scope
     PyObject* py_sim_handle = PyLong_FromVoidPtr(sim);
                                                  ^~~
```
(and bunch of additional errors, don't want to spam with them too much)

Did you encounter this?

_(ps: I hope I have set up all the dependencies correctly, I'll double check - it's just that maybe you have had the same issues)
(ps2: worst case scenario this error is my fault, but then this can still serve as a guide to anyone else who gets into similar troubles...)_

**Comment by asaparov** [comment]
Ah yeah, this is because I've been changing the C-side code a lot but haven't been updating the C-Python interface in api/python/nel/simulator.cpp, so there are definitely going to be errors. I was planning to fix those later, once the C-side is more complete.

**Comment by asaparov** [comment]
If you want to work on visualization, I think you can ignore the interface for now, and write the visualization code assuming the C-Python interface is working, and maybe test with some simple synthetic examples. But if you prefer, you're totally welcome to help fix the C-Python interface.
